create-commerce-pay-url:
  path: '/api/commerce/pay/new'
  controller: Viabo\Backend\Controller\management\commercePay\CommercePayCreatorController
  methods: POST

create-commerce-virtual-terminal-pay:
  path: '/api/commerce/virtual/pay'
  controller: Viabo\Backend\Controller\management\commercePay\CommercePayVirtualTerminalCreatorController
  methods: POST
