export const PROCESS_LIST = {
  REGISTER: 'REGISTRO',
  VALIDATION_CODE: 'CODIGO DE VALIDACIÓN',
  CONTINUE_PROCESS: 'CONTINUAR PROCESO',
  SERVICES_SELECTION: 'SELECCION DE SERVICIOS',
  COMMERCE_INFO: 'INFORMACIÓN DEL COMERCIO',
  COMMERCE_DOCUMENTATION: 'DOCUMENTOS DEL COMERCIO'
}
