export const PROCESS_LIST = {
  REGISTER: 'REGISTRO',
  VALIDATION_CODE: 'CODIGO DE VALIDACIÓN',
  SERVICES_SELECTION: 'SELECCION DE SERVICIOS',
  COMMERCE_INFO: 'INFORMACIÓN DEL COMERCIO',
  CONTINUE_PROCESS: 'CONTINUAR PROCESO'
}
