stock-cards-find:
  path: '/api/cards/stock'
  controller: Viabo\Backend\Controller\management\card\StockCardsFinderController
  methods: GET

commerce-cards-find:
  path: '/api/cards/commerce'
  controller: Viabo\Backend\Controller\management\card\CommerceCardsFinderController
  methods: GET

card-information-find:
  path: '/api/card/information/{cardId}'
  controller: Viabo\Backend\Controller\management\card\CardInformationFinderController
  methods: GET