stock-cards-find:
  path: '/api/cards/stock'
  controller: Viabo\Backend\Controller\management\card\StockCardsFinderController
  methods: GET

enabled-commerce-cards-find:
  path: '/api/enabled-cards/commerce'
  controller: Viabo\Backend\Controller\management\card\EnabledCommerceCardsFinderController
  methods: GET

disabled-commerce-cards-find:
  path: '/api/disabled-cards/commerce'
  controller: Viabo\Backend\Controller\management\card\DisabledCommerceCardsFinderController
  methods: GET

card-information-find:
  path: '/api/card/information/{cardId}'
  controller: Viabo\Backend\Controller\management\card\CardInformationFinderController
  methods: GET

main-card-information-find:
  path: '/api/main-card/information'
  controller: Viabo\Backend\Controller\management\card\MainCardInformationFinderController
  methods: GET