find-stock-cards:
  path: '/api/cards/stock'
  controller: Viabo\Backend\Controller\management\card\StockCardsFinderController
  methods: GET

find-enabled-cards-of-commerce:
  path: '/api/enabled-cards/commerce'
  controller: Viabo\Backend\Controller\management\card\EnabledCommerceCardsFinderController
  methods: GET

find-disabled-cards-of-commerce:
  path: '/api/disabled-cards/commerce'
  controller: Viabo\Backend\Controller\management\card\DisabledCommerceCardsFinderController
  methods: GET

find-card-information:
  path: '/api/card/information/{cardId}'
  controller: Viabo\Backend\Controller\management\card\CardInformationFinderController
  methods: GET

find-card-demo-information:
  path: '/api/card-demo/information/{cardNumber}'
  controller: Viabo\Backend\Controller\management\card\CardDemoInformationFinderController
  methods: GET

main-card-information-find:
  path: '/api/main-card/information'
  controller: Viabo\Backend\Controller\management\card\MainCardInformationFinderController
  methods: GET

find-payment-processor-of-commerce:
  path: '/api/payment-processors/of/commerce'
  controller: Viabo\Backend\Controller\management\card\PaymentProcessorsCommerceFinderController
  methods: GET