finder-commerce:
  path: '/api/commerce/legal-representative'
  controller: Viabo\Backend\Controller\business\commerce\CommerceFinderController
  methods: GET

finder-commerces:
  path: '/api/commerces'
  controller: Viabo\Backend\Controller\business\commerce\CommercesFinderController
  methods: GET

finder-commerce-affiliates:
  path: '/api/commerces/affiliates'
  controller: Viabo\Backend\Controller\business\commerce\CommerceAffiliatesFinderController
  methods: GET