update-user-data-by-stock-cards:
  path: '/api/card-owner/data/update'
  controller: Viabo\Backend\Controller\security\user\update\CardOwnerDataUpdaterController
  methods: PUT

reset-password-user-by-card-owner:
  path: '/api/card-owner/password/reset/{userId}'
  controller: Viabo\Backend\Controller\security\user\update\CardOwnerPasswordUpdaterController
  methods: PUT

reset-password-user:
  path: '/api/user/password/reset'
  controller: Viabo\Backend\Controller\security\user\update\UserPasswordUpdaterController
  methods: PUT

reset-user-password-by-url:
  path: '/api/user/password/reset/{userId}'
  controller: Viabo\Backend\Controller\security\user\update\UpdateUserPasswordByUrlController
  methods: GET