find-subaccounts-cards:
  path: '/api/cardCloud/sub-account/{subAccountId}/cards'
  controller: Viabo\Backend\Controller\stp\cardCloud\find\CardCloudSubAccountCardsFinderController
  methods: GET

find-card-details:
  path: '/api/cardCloud/card/{cardId}/details'
  controller: Viabo\Backend\Controller\stp\cardCloud\find\CardCloudCardDetailsFinderController
  methods: GET
