create-commerce-pay-transaction:
  path: '/api/commerce/pay-transaction/new'
  controller: Viabo\Backend\Controller\management\commerceTransaction\CommerceTransactionCreatorController
  methods: POST
