finder-commerce-pay-all-transactions:
  path: '/api/commerces-pay/transactions/all'
  controller: Viabo\Backend\Controller\management\commerceTransaction\CommerceTransactionsFinderController
  methods: GET
