finder-commerce-to-register:
  path: '/api/commerce/legal-representative'
  controller: Viabo\Backend\Controller\business\commerce\CommerceFinderByLegalRepresentativeController
  methods: GET

finder-commerces:
  path: '/api/commerces'
  controller: Viabo\Backend\Controller\business\commerce\CommercesFinderController
  methods: GET

finder-commerce-affiliates:
  path: '/api/commerces/affiliates'
  controller: Viabo\Backend\Controller\business\commerce\CommerceAffiliatesFinderController
  methods: GET

finder-commerce:
  path: '/api/commerce/{commerceId}'
  controller: Viabo\Backend\Controller\business\commerce\CommerceFinderController
  methods: GET

find-commerce-slug:
  path: "/api/commerce-slug/{slug}"
  controller: Viabo\Backend\Controller\business\commerce\CommerceSlugFinderController
  methods: GET