find-funding-order:
  path: "/funding-order/referenceNumber/{referenceNumber}"
  controller: Viabo\Backend\Controller\management\fundingOrder\FundingOrderViewController
  methods: GET

find-funding-orders:
  path: "/api/funding-orders"
  controller: Viabo\Backend\Controller\management\fundingOrder\FundingOrderFinderController
  methods: GET
