find-company-by-register-of-outside:
  path: '/api/commerce/legal-representative'
  controller: Viabo\Backend\Controller\backoffice\company\CompanyFinderByUserController
  methods: GET

finder-companies:
  path: '/api/commerces'
  controller: Viabo\Backend\Controller\backoffice\company\find\CompaniesFinderController
  methods: GET

find-companies-by-card-cloud-service:
  path: '/api/commerces/card-cloud-service'
  controller: Viabo\Backend\Controller\backoffice\company\find\CompaniesByCardCloudServiceFinderController
  methods: GET

finder-commerce-affiliates:
  path: '/api/commerces/affiliates'
  controller: Viabo\Backend\Controller\backoffice\company\CommerceAffiliatesFinderController
  methods: GET

finder-commerce:
  path: '/api/commerce/{commerceId}'
  controller: Viabo\Backend\Controller\backoffice\company\CommerceFinderController
  methods: GET

find-sub-account-company:
  path: '/api/commerce/{companyId}/sub-account'
  controller: Viabo\Backend\Controller\backoffice\company\find\CompanySubAccountFinderController
  methods: GET

find-sub-account-company-movements:
  path: '/api/commerce/{companyId}/sub-account/movements'
  controller: Viabo\Backend\Controller\backoffice\company\find\CompanySubAccountMovementsFinderController
  methods: GET

find-commerce-slug:
  path: "/api/commerce-slug/{slug}"
  controller: Viabo\Backend\Controller\backoffice\company\CommerceSlugFinderController
  methods: GET

finder-company-by-service-stp:
  path: '/api/backoffice/company/{company}'
  controller: Viabo\Backend\Controller\backoffice\company\find\CompanyFinderController
  methods: GET
