update-commerce-by-registration:
  path: '/api/commerce/update'
  controller: Viabo\Backend\Controller\backoffice\company\CommerceUpdaterByRegistrationController
  methods: PUT

update-commerce-by-backoffice:
  path: '/api/backoffice/commerce/update'
  controller: Viabo\Backend\Controller\backoffice\company\CommerceUpdaterByBackofficeController
  methods: POST

update-commerce-for-disable-and-enable:
  path: '/api/backoffice/company/toggle'
  controller: Viabo\Backend\Controller\backoffice\company\update\CompanyToggleController
  methods: PUT