commerce-register:
  path: "/comercio/registro"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

cards-register:
  path: "/registro"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

auth-paths:
  path: "/auth/{any}"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET
  requirements:
    any: ".+"

commerce:
  path: "/commerce"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

commerce-paths:
  path: "/commerce/{any}"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET
  requirements:
    any: ".+"

management:
  path: "/management"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

management-paths:
  path: "/management/{any}"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET
  requirements:
    any: ".+"

charge:
  path: "/cobro"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

charge-paths:
  path: "/cobro/{any}"
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET
  requirements:
    any: ".+"
