default:
  path: '/dashboard'
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

frontend:
  path: '/dashboard/{path?}'
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET
