default:
  path: '/management'
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET

frontend:
  path: '/management/{path?}'
  controller: Viabo\Backend\Controller\RoutesFrontendController
  methods: GET
