find-card-movements:
  path: '/api/card/{cardId}/movements/{initialDate}/to/{finalDate}'
  controller: Viabo\Backend\Controller\management\cardMovement\CardMovementsFinderController
  methods: GET

notifications-cards-movements:
  path: '/api/notifications/cards/movements'
  controller: Viabo\Backend\Controller\management\cardMovement\CardMovementsNotifierController
  methods: GET

notifications-cards-masters-movements:
  path: '/api/notifications/cards-masters/movements'
  controller: Viabo\Backend\Controller\management\cardMovement\CardsMastersMovementsNotifierController
  methods: GET

find-cards-master-movements:
  path: '/api/cards/movements/{initialDate}/to/{finalDate}'
  controller: Viabo\Backend\Controller\management\cardMovement\CardsMasterMovementsFinderController
  methods: GET
